### ISSUE TITLE
Changes appear to be processed character by character (VsCoq2 )

### ISSUE THREAD

**Issue by nathanwhit** [coq/vscoq#682]
Often if I modify a proof, it takes a long time to update the goals view with the changes, but more notably, it appears that the document (at least, the proof being modified and all following proofs) is re-executed for each typed character. In other words, if I type 8 characters, the document is re-executed 8 times. The following video illustrates this fairly well:
https://github.com/coq-community/vscoq/assets/17734409/fc5f7897-9ed4-4a90-af95-faf047926745

The problem is most noticeable in larger files, but I've also encountered it in smaller files.

I would expect that receiving a new `documentDidChange` notification for a given document would cancel any ongoing work handling earlier change notifications for that document, but instead, it almost looks like the change notifications just pile up and get processed sequentially.

**Comment by Blaisorblade** [comment]
I agree with this issue — and even with manual mode, my impression is that the file is re-parsed after every keypress.

And this issue makes VsCoq2 unusable for me at the moment.
