### ISSUE TITLE
Parsing issues with MetaCoq

### ISSUE THREAD

**Issue by thomas-lamiaux** [coq/vscoq#892]
At the moment, basically all the files in https://github.com/thomas-lamiaux/generating_recursors creates parsing issue. 
I can not exactly isolate a file as it happens from time to time when I open files. 

You can check out the issue by cloning the repo, doing make, and trying to check the files in the folder recursors_api.

I am using coq 8.19.2, the associated version of Equations and MetaCoq and vscoq 2.1.7.

**Comment by terencode** [comment]
Not sure if it is the same, but for my project, the parsing is messed up almost each time I edit something containing utf8 characters like 𝓘 or 𝒯.  The only fix is to reopen vscode, which gets annoying very quickly.

**Comment by gares** [comment]
@terencode can you please tell us which version are you on?

**Comment by terencode** [comment]
> @terencode can you please tell us which version are you on?

vscoq 2.2.1

**Comment by thomas-lamiaux** [comment]
see https://coq.zulipchat.com/#narrow/channel/237662-VsCoq-devs-.26-users/topic/VsCoq.20randomly.20crashes.20when.20opening.20a.20file/near/481334265 for a minimal example. 
Basically it happens as soon as there is a file doing 
```
From MetaCoq Require Import Template.All
```

**Comment by SkySkimmer** [comment]
can you try with https://github.com/coq/coq/pull/19864 ?

**Comment by SkySkimmer** [comment]
It doesn't even work, `set_option_value ~stage:Interp (fun _ v -> v) key i` sets the option to the current value

**Comment by gares** [comment]
Thanks for investigating @SkySkimmer . Should we open an issue in metacoq?

**Comment by SkySkimmer** [comment]
https://github.com/MetaCoq/metacoq/pull/1123

**Comment by gares** [comment]
Thomas can you confirm the issue is no more present?

**Comment by thomas-lamiaux** [comment]
I don't work with the master right now, but I have been confirmed by @MathisBD that it is so I think it is fine closing

**Comment by MathisBD** [comment]
Yes the issue is solved in MetaCoq's main branch, you can close

**Comment by thomas-lamiaux** [comment]
Solved by Gaetan's PR
