### ISSUE TITLE
Setting PATH for forked programs with coq extensions (QuickChick) ?

### ISSUE THREAD

**Issue by mwhicks1** [coq/vscoq#930]
I'm trying to use VSCoq along with QuickChick. I am getting an error that when trying to run QuickChick it cannot find `ocamlbuild` in order to build and execute the quickcheck tests:
```
Could not compile test program: /var/folders/8d/bt1pyh894313lkwr0f8y5z780000gr/T/QuickChick/165155_4c0838/QuickChick12913f.ml

Build stderr:
sh: ocamlbuild: command not found
```
This error arises for the [Introduction.v](https://softwarefoundations.cis.upenn.edu/qc-current/Introduction.html) file in the [Software Foundations QuickChick volume](https://softwarefoundations.cis.upenn.edu/qc-current/index.html) (which you can download from [here](https://softwarefoundations.cis.upenn.edu/qc-current/qc.tgz)), when I try to do the `QuickChick removeP.` command (right toward the front).

I installed VSCoq using `opam` as prescribed in the [README](https://github.com/coq/vscoq/blob/main/README.md). I have version 2.2.1 and Coq 8.18.0. I installed QuickChick also with opam, via `opam install coq-quickchick` after running `opam repo add coq-released https://coq.inria.fr/opam/released`.

I find that if I symlink my opam `bin` directory into `/user/local/bin/` the error goes away. So there's something about the `PATH` configuration that is messed up. I.e., if I do the following and then try to run `QuickChick removeP.` it works:
```
for file in /Users/mwhicks/.opam/4.14/bin/*; do sudo ln -s $file /usr/local/bin/`basename $file`; done
```
Perhaps I need to configure VSCoq some way I'm not aware of, or else there needs to be a way to instruct it in the default PATH to use for Coq extensions? I don't know how QuickChick works so I'm not sure.

**Comment by gares** [comment]
This might be related to vscoq (and electron apps). How do you start code? A few remarks:
- if you open a shell, you check that ocamlbuild is in your PATH, and then you start code from there (and you have no other code windows open), does it work?
- not that the PATH you may set in the embedded code terminal does not affect the value of the variable used by vscoqtop, only the value before you start code
- if you have multiple code windows, I think there is (maybe there was) a limitation of electron (hence code) that only the env variable of the first window of code are taken into account. E.g. the second window you open inherits the environment from the first window, not from the shell you start code from

Given the mess above, a suggestion: if you `exec` from quickchick (hence from vscoqtop) you could add the path of vsqcoqtop (eg via ocaml's `executable_name` and `dirname`) to the PATH explicitly (either via passing an explicit env to `Unix.fork` or by using `Unix.setenv` which is not called like that in caml but now I don't recall exactly how it is named).

Hope it helps.

**Comment by mwhicks1** [comment]
> if you open a shell, you check that ocamlbuild is in your PATH, and then you start code from there (and you have no other code windows open), does it work?

Yes! In fact, if I just quit VSCode, open it, and then open my Coq development, that works too. It wasn't working yesterday.

> if you have multiple code windows, I think there is (maybe there was) a limitation of electron (hence code) that only the env variable of the first window of code are taken into account. E.g. the second window you open inherits the environment from the first window, not from the shell you start code from

I believe that this was probably the issue. I had a remote window opened when I started and tried to run QuickChick, and I suspect that the PATH from that window, which does not relate at all to my local environment, was getting used.

Thanks for the help! CC @lemonidas in case he wants to try out your suggestion on enhancing the PATH from QuickChick.
