### ISSUE TITLE
enhancement: place cursor at error

### ISSUE THREAD

**Issue by ybertot** [coq/vscoq#952]
In manual mode, when executing a command that raises an error, the location of the error is correctly highlighted in the faulty command, but the cursor is place at the end of the last correctly executed command.

The way syntax errors is handled is also awkward.  When trying to execute the next command, it does not fail if there is a syntax error (but it probably should), instead it tries to execute the next correctly formed command (which often out of context, or made of fragments that were not intended by the user).

**Comment by rtetley** [comment]
I need more context: where should I place the cursor ? At the end of the errored command ?
Concerning the parse errors this is a known issue, see #877.

**Comment by ybertot** [comment]
Let's concentrate on the first paragraph of my issue.  I would like the cursor to be place at the end of the text that is highlighted with the red mark.

**Comment by ybertot** [comment]
![Screenshot at 2024-12-11 11-18-16](https://github.com/user-attachments/assets/919267ec-5b4f-4803-90c1-cb24b2e273e6)

Just after word "titi" in this case.

**Comment by rtetley** [comment]
I have a conceptual problem with this. Until now, in manual mode step forward and backward are related to the executed area. If a sentence is errored it is not executed. So take the example here:
<img width="675" alt="Screenshot 2024-12-11 at 11 30 23" src="https://github.com/user-attachments/assets/d35de622-ff27-48f4-87c3-440fb6144ff9">
After stepping through the error, if I do a step backward, I will then end up here:
<img width="675" alt="Screenshot 2024-12-11 at 11 32 04" src="https://github.com/user-attachments/assets/3f0c1710-ff03-4208-9113-672733af79c4">
Does this seem right to you ?

**Comment by ybertot** [comment]
I don't understand the problem.  If the step forward failed because of an error, then it was not executed, so I do not consider this as "stepping through the error" and I do not need to take a step backward.
